### ISSUE TITLE
style.min.css  auto import giving error.

### ISSUE THREAD

**Issue by shambhu384** [Mezcalito/ux-filemanager#2]
"./node_modules/@symfony/stimulus-bridge/dist/webpack/loader.js!./assets/controllers.json" contains a reference to the file "@mezcalito/ux-filemanager/dist/style.min.css".
This file can not be found, please check it for typos or update it if the file got moved.

Thank you for creating wonderful filemanager.

**Comment by loicsapone** [comment]
Hi @shambhu384, thanks for your issue!

It's fixe and include in a new release https://github.com/Mezcalito/ux-filemanager/releases/tag/0.1.2
You can try to reinstall the package in your application or update the auto import path in your application like this:

```diff
{
    "controllers": {
        ...
        "@mezcalito/ux-filemanager": {
            "filemanager": {
                "enabled": true,
                "fetch": "eager",
                "autoimport": {
-                   "@mezcalito/ux-filemanager/dist/style.min.css": true
+                   "@mezcalito/ux-filemanager/dist/styles.min.css": true
                }
            }
        },
        ...
    },
    "entrypoints": []
}
```
